# This contains all the default values for commandline arguments
# Path values are not included because they are machine specific

ide: "none"
framework: "cosa"
platform: "avr"
port: "none"
version: "0.0.1"
board: "uno"
btarget: "default"        # build target
utarget: "default"    # upload target
