libraries:
  lib1:
    url: url
    version: ver
    path: path
    compile_flags: []

  lib2:
    url: url
    version: ver
    path: path
    compile_flags: []

dependencies:
  dep1:
    name:
    url: url
    version: ver
    compile_flags: []

  dep2:
    name:
    url: url
    version: ver
    compile_flags: []
