dist: trusty
language: python
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc avrdude -y
  - pip install --upgrade pip
  - pip install tox
  - pip install --upgrade flake8
script:
  - tox
  - cd toolchain
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake ../
  - make
